/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux higo-Latitude-3440 3.13.0-32-generic x86_64"
#define LGL_COMPILED "Qua Nov 26 18:35:34 AMT 2014"
#define LGL_RELEASED "Wed Oct 29 15:03:13 CET 2014"
#define LGL_VERSION "azd"
#define LGL_ID "0d997521ad2e7d4e94f5d74a4665455b91309b62"
