/**********************************************************/
/* Automatically generated by './mkconfig': do note edit! */
/**********************************************************/
#define BTOR_CC "gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-7)"
#define BTOR_CFLAGS "-W -Wall -Wextra -O3 -DNDEBUG -DNBTORLOG -DBTOR_USE_LINGELING -DBTOR_ENABLE_BETA_REDUCTION_PROBING"
#define BTOR_OS "Linux localhost.localdomain 3.17.3-200.fc20.x86_64 x86_64"
#define BTOR_COMPILED "Tue Nov 25 20:03:07 AMT 2014"
#define BTOR_RELEASED "Wed Oct 29 15:03:13 CET 2014"
#define BTOR_VERSION "2.0.1"
#define BTOR_ID "bfafa40e5e4c9eb43e92bab7fa7095f5c0d4a421"
